# 포트 설정
server:
  port: 8093

# JWT 설정
jwt:
  jwtSecret: "aVeryLongSecretKeyThatIsAtLeast32BytesLongForSecurity"
  jwtExpiration: 3600000 # 1시간 (밀리초 단위)

# 스프링 설정
spring:
  # 애플리케이션 이름 설정
  application:
    name: talk-service

  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/talk
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  # MongoDB 설정
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017
      database: talk  # 원하는 데이터베이스 이름

  # JPA 설정
  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  # 카프카 설정
  kafka:
    consumer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
      group-id: talk-group
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

# gRPC 서버 포트 설정
grpc:
  server:
    port: 50052
  client:
    member-grpc-server: # @GrpcClient에서 사용한 이름과 일치해야 함
      address: static://localhost:50051  # gRPC 서버 주소와 포트
      negotiationType: plaintext  # SSL/TLS 없이 평문으로 통신할 경우

# msa 로깅 설정 (jaeger)
otel:
  resource:
    attributes:
      service.name: ${spring.application.name}

tracing:
  url: http://localhost:4318/v1/traces

# 스프링 부트 액추에이터 설정
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: always
#    security:
#      enabled: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'