# 포트 설정
server:
  port: 8093

# JWT 설정
jwt:
  jwtSecret: "aVeryLongSecretKeyThatIsAtLeast32BytesLongForSecurity"
  jwtExpiration: 3600000 # 1시간 (밀리초 단위)

# 스프링 설정
spring:
  # 애플리케이션 이름 설정
  application:
    name: talk-service

  # Eureka 설정
  cloud:
    discovery:
      enabled: true

  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/talk
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  # 카프카 설정
  kafka:
    consumer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
      group-id: talk-group
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

# Eureka 설정 (spring 하위에서 최상위로 이동)
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      grpcPort: ${grpc.server.port}

# gRPC 서버 포트 설정
grpc:
  server:
    port: 50053
  client:
    member-grpc-server:                    # @GrpcClient에서 사용한 이름과 일치해야 함
      address: discovery:///member-service # gRPC 서버 주소와 포트 (유레카 서비스 이름 사용)
      negotiationType: plaintext           # SSL/TLS 없이 평문으로 통신할 경우
      enableKeepAlive: true
      keepAliveWithoutCalls: true

# msa 로깅 설정 (jaeger)
otel:
  resource:
    attributes:
      service.name: ${spring.application.name}

tracing:
  url: http://localhost:4318/v1/traces

# 스프링 부트 액추에이터 설정
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: always
#    security:
#      enabled: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'